version: '3.4'

services:
  mongo:
    container_name: mongo
    restart: always
    volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
     - "27017:27017"
  todolist.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro